# Generated by Django 6.1.1 on 2026-10-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='etiqueta',
        ),
        migrations.AddField(
            model_name='cuenta',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, related_name='cuenta', to='gestion.etiqueta'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='tipo',
            field=models.CharField(choices=[('RETIRO', 'Retiro'), ('TRANSFERENCIA', 'Transferencia'), ('DEPOSITO', 'Deposito')], max_length=20),
        ),
    ]
