# Generated by Django 6.1.1 on 2026-10-04 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_remove_cuenta_etiqueta_cuenta_etiquetas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='tipo',
            field=models.CharField(choices=[('DEPOSITO', 'Deposito'), ('RETIRO', 'Retiro'), ('TRANSFERENCIA', 'Transferencia')], max_length=20),
        ),
    ]
